# Generated by Django 2.2 on 2022-02-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acai_App', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='acai',
            name='beverage',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
